language: python
python:
    - '2.7'

jobs:
  include:
    - stage: build-containers
      script: ./assignment-cictcd.sh -b
    - stage: test-deploy
      script: ./assignment-cictcd.sh -d
    - stage: unit-test
      script: ./assignment-cictcd.sh -t

os:
  - linux


notifications:
  email:
    recipients:
      - ezhilkani.govindarajan@sjsu.edu
      - chaitanya.lala@sjsu.edu
      - venkatasatyaphanipavan.chitturikumar@sjsu.edu
      - parthasarathi.ghosh@sjsu.edu
    on_success: always # default: change
    on_failure: always # default: always
